We saw ternary expressions in list, dict and set conditions

numpy.where function is a vectorised version of the ternary expression ‘x if condition else y’

np.where makes it easy to produce a new array of values based on another array (example 2)

In [2]:
import numpy as np
#create two arrays of values and one boolean
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5, 1.6])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5, 2.6])
cond = np.array([True, False, False, True, True, False])

#lets take a value from xarr when cond is True. Otherwise take a value from yarr
result = [(x if c else y)
         for x, y, c in zip(xarr, yarr, cond)]

result


[1.1, 2.2, 2.3, 1.4, 1.5, 2.6]

##### This method has two problems:
- Not fast for large arrays
- wont work with multidimensional arrays

#### np.where  should be used
The below can be read as "where the condition is true, select xarr, otherwise yarr"

In [3]:
np.where(cond, xarr, yarr)

array([1.1, 2.2, 2.3, 1.4, 1.5, 2.6])

In [5]:
#Example 2
#We want all postive values to be returned as 2 from an existing array: 
arr = np.random.randn(4,4)
arr

array([[-0.93957868,  0.0116647 , -0.35891262, -0.21249576],
       [-0.89775923,  0.34757739, -0.71215222, -0.46315864],
       [-1.89524564, -0.5157547 ,  1.23900078, -1.83274867],
       [ 0.92740988, -0.5420169 ,  0.51299057,  0.79363744]])

In [6]:
arr>0

array([[False,  True, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [ True, False,  True,  True]])

In [7]:

np.where(arr>0, 2, -2)

array([[-2,  2, -2, -2],
       [-2,  2, -2, -2],
       [-2, -2,  2, -2],
       [ 2, -2,  2,  2]])

In [8]:
#if we want minus figure to remain as is:
np.where(arr>0, 2, arr)

array([[-0.93957868,  2.        , -0.35891262, -0.21249576],
       [-0.89775923,  2.        , -0.71215222, -0.46315864],
       [-1.89524564, -0.5157547 ,  2.        , -1.83274867],
       [ 2.        , -0.5420169 ,  2.        ,  2.        ]])