## Universal Functions List
- abs, fabs= compute the absolute value element wise
- sqrt= square root
- square= square of each element
- exp= compute the exponant e of each element
- sign = compute the sign of each element
- rint = round elements to the nearest integer, preserving the dtype.
- modf = return fractional and integral parts of array as a seperat array.

## Binary Universal Functions
—> These are performed element wise

- add
- subtract
- multiply
- divide, floor_divide
- power
- maximum, fmax
- minimum, fmin
- mod = element wise modulas
- copysign = copy sign of values in second argument to values in first argument
- greater, greater_equal, less, less_equal, equal, not_equal
—> These perform element wise comparison, yeilding boolean arrays

## Unique and Other Set Logic
NumPy has some basic set operations for 1d arrays
- .unique(x): returns the unique values in an array
- intersect1d(x, y): compute the sorted, common elements in x and y
- union1d(x, y): sorted union elements of both


## Sorting
Like lists, we can use the sort() methods here.


In [3]:
import numpy as np
arr = np.random.randn(15)
arr

array([ 0.96317899,  0.92865422, -0.80610571, -1.68434113, -2.00292942,
       -2.18421477,  3.21200548,  1.5520026 ,  1.20757943, -1.83199378,
       -0.31073804,  1.29320767,  0.4659605 ,  1.31173593, -0.24254538])

In [5]:
arr.sort()
arr

array([-2.18421477, -2.00292942, -1.83199378, -1.68434113, -0.80610571,
       -0.31073804, -0.24254538,  0.4659605 ,  0.92865422,  0.96317899,
        1.20757943,  1.29320767,  1.31173593,  1.5520026 ,  3.21200548])

In [7]:
#to sort with a multidimensional array we can pass the axis to the sort method
arr = np.random.randn(15).reshape((5,3))
arr

array([[ 0.99710785,  1.60531299,  0.70234427],
       [ 0.91335247, -0.89934055, -0.66296206],
       [-0.42683927, -0.5214154 ,  0.62827036],
       [ 0.59368892, -1.81979028,  0.25589479],
       [ 2.31834438,  0.20667991,  0.49956061]])

In [9]:
#axis 1. Could also be written as (axis=1)
arr.sort(1)
arr

array([[ 0.70234427,  0.99710785,  1.60531299],
       [-0.89934055, -0.66296206,  0.91335247],
       [-0.5214154 , -0.42683927,  0.62827036],
       [-1.81979028,  0.25589479,  0.59368892],
       [ 0.20667991,  0.49956061,  2.31834438]])

In [10]:
arr.sort(0)
arr

array([[-1.81979028, -0.66296206,  0.59368892],
       [-0.89934055, -0.42683927,  0.62827036],
       [-0.5214154 ,  0.25589479,  0.91335247],
       [ 0.20667991,  0.49956061,  1.60531299],
       [ 0.70234427,  0.99710785,  2.31834438]])

# Mathematical & Statistical Models

A set of mathematical functions that compute statistics about an entire array or about the data along an axis are accessible as methods of an array class

In [12]:
arr = np.random.randn(4,5)
arr

array([[-0.74768134,  0.43827181, -1.70076571,  0.11609283, -0.10896003],
       [-1.70520187,  0.19114431,  0.45530264,  1.1216545 , -0.60338584],
       [-0.94298727, -0.03732501, -0.73144267,  0.51527147,  0.43491838],
       [-0.11800158,  0.54731791,  1.16632194,  0.99876185, -0.71408404]])

In [13]:
arr.sum()

-1.424777715078812

In [14]:
#can also be written as np.mean(arr)
arr.mean()

-0.07123888575394059

In [15]:
#These also take optional axis arguments
arr.mean(axis=1)
#this mean computes across the columns

array([-0.40060849, -0.10809725, -0.15231302,  0.37606322])

In multidimensional arrays, accumulation functions like cumsum return an array of the same size, but with the partial aggregates computed along the indicated axis according to each lower dimensional slice:


In [16]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [18]:
arr.cumsum(0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [19]:
arr.cumsum(1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

#### Other Methods 
- arr.std, var: standard deviation and variance
- min, max
- cumsum: cumulative sum of elements starting from 0
- cumprod: cumulative product of elements starting from 1

# Methods for Boolean Arrays
Boolean arrays are coerced to 1(True) and 0(False) in the preceding methods. Thus, sum is often used as a means of counting True values in a boolean array:

In [21]:
arr = np.random.randn(100)
arr[:11]

array([ 0.30267363,  0.05388517, -0.27134356, -0.5836089 , -1.07560773,
       -1.17005431,  0.91818918,  0.30576149, -0.16087302,  0.5446128 ,
        1.43852702])

In [22]:
#count the number of positive values
(arr>0).sum()

55

The following works with boolean arrays

- all(): Checks if every value is True
- any(): tests whether one or more values in an array is True

In [24]:
arr = np.array([True, False, True, False])
arr.any()

True

In [25]:
arr.all()

False