## Arithmetic with NumPy Arrays
Arrays enable you to express batch operations on data without writing any for loops. This is called Vectorisation. 
Any arithmetic operations between equal-size arrays applies the operation element wise.

Need to look into Matrices artithmetic more

In [4]:
import numpy as np
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [6]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [9]:
arr1 = np.array([[1,2,3],[3,7,8]])
arr>arr1

array([[False, False, False],
       [ True, False, False]])