## Basic Indexing & Slicing
Useful way to subset your data or individual elements. 

Works similar to indexing lists

In [1]:
import numpy as np

In [2]:
arr = np.arange(15)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr[5]

5

In [5]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [7]:
#Lets slice some data and modify the original array. 
arr_mod = arr[3:8]
arr_mod

array([3, 4, 5, 6, 7])

In [8]:
arr_mod[:] = 18

In [9]:
arr

array([ 0,  1,  2, 18, 18, 18, 18, 18,  8,  9, 10, 11, 12, 13, 14])

arr_slice in this case is called a view. Changes to this view will be reflected in the original array. Use .copy() to prevent changes being made.

With higher dimensional arrasy, you have more options. In 2-d arrays, the elements at each index are no longer scalars but rather 1-d arrays:
### 2d Array

In [14]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
#lets index an array
arr2[1]

array([4, 5, 6])

In [15]:
#if I wanted to index the middle element of this array:
arr2[1, 1]

5

In [16]:
#This can also be written as:
arr2[1][1]

5

### 3d Array

In [25]:
arr3 = np.array([[
    [1,2,3],[4,5,6]],
    [[3,5,6], [8,3,5]],
])


In [20]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 5, 6],
        [8, 3, 5]]])

In [31]:
arr3.shape

(2, 2, 3)

In [33]:
#Selects a 2x3 array
arr3[1]

array([[3, 5, 6],
       [8, 3, 5]])

In [39]:
arr3[1,0]

array([3, 5, 6])

In [40]:
arr3[1,0][1]

5

In [43]:
#assigning values
mod = arr3[1,0].copy()
mod

array([3, 5, 6])

In [44]:
mod[:] = 43 

In [45]:
mod

array([43, 43, 43])

In [46]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 5, 6],
        [8, 3, 5]]])

In [52]:
arr3[1,0] = mod

In [54]:
arr3[1,0,:]

array([43, 43, 43])

In [55]:
x = arr3[1]

In [56]:
x[:]

array([[43, 43, 43],
       [ 8,  3,  5]])

In [59]:
x[1] = [7,8,9]
x[0] = [4,5,6]

In [60]:
x

array([[4, 5, 6],
       [7, 8, 9]])

In [61]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [7, 8, 9]]])

### Indexing with Slices


In [62]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
#begin on the first row, select 6 values
arr2[1:6]

array([[4, 5, 6],
       [7, 8, 9]])

In [64]:
#Read as selecting the first two rows
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
#first two rows, first value in the first column
arr2[:2, :1]

array([[1],
       [4]])