## Boolean Indexing
Comparison operators such as == are also vectorised for arrays.
Can use: 

==
!=
Cannot use ‘and’ or ‘or’
Instead use & and |

In [2]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [3]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [5]:
mask = (names == 'Bob')|(names == 'Joe')
mask

array([ True,  True, False,  True, False,  True,  True])

In [12]:
#Set all negative values in a dataset to 0
data = np.random.randn(16).reshape(4,4)
data

array([[-0.96891991,  0.53448782,  0.23687806,  0.23763652],
       [ 0.02988676, -1.62418057, -0.00733162, -0.20251617],
       [ 2.44734905, -0.49826061, -1.43733084,  0.44295575],
       [-0.92878214, -0.19023754,  0.11679204, -1.90388659]])

In [15]:
data[data < 0] = 0
non_neg = data
non_neg

array([[0.        , 0.53448782, 0.23687806, 0.23763652],
       [0.02988676, 0.        , 0.        , 0.        ],
       [2.44734905, 0.        , 0.        , 0.44295575],
       [0.        , 0.        , 0.11679204, 0.        ]])

In [13]:
data

array([[-0.96891991,  0.53448782,  0.23687806,  0.23763652],
       [ 0.02988676, -1.62418057, -0.00733162, -0.20251617],
       [ 2.44734905, -0.49826061, -1.43733084,  0.44295575],
       [-0.92878214, -0.19023754,  0.11679204, -1.90388659]])