## Fancy Indexing
Term to describe integer arrays.



In [1]:
import numpy as np
arr = np.random.randn(4,4)

In [2]:
arr

array([[-0.3985533 ,  0.37323705, -1.21704115, -0.19394048],
       [ 2.22050946,  0.30662169, -1.35559547,  0.22127259],
       [-0.43562565,  1.3504675 , -0.93730754, -1.09637638],
       [-0.00880795,  0.11667467,  0.16259965,  2.07114436]])

In [5]:
#To select a subset of rows in a particular order, you can pass a list or ndarray of intergers specifiying the desired order
arr[[3,1,0]]

#Negative indices can also be used

array([[-0.00880795,  0.11667467,  0.16259965,  2.07114436],
       [ 2.22050946,  0.30662169, -1.35559547,  0.22127259],
       [-0.3985533 ,  0.37323705, -1.21704115, -0.19394048]])

Passing multiple arrays does something slightly different; it selects a 1-d array of elements corresponding to each tuple of indices

In [10]:
arr1 = np.arange(32).reshape((8,4))

In [7]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [14]:
arr1[[1,3,6,3],[2,1,0,2]]

array([ 6, 13, 24, 14])