# NumPy ndarry: A Multidimensional Array Object

Fast, flexible container for large datasets in Python


In [1]:
import numpy as np

## Creating ndarrays

Easiest way is to use the array function. This accepts any secquence-like object and produces a new NumPy array containing the passed data.

In [2]:
data = [1,2,3,4,5]
arr = np.array(data)
arr

array([1, 2, 3, 4, 5])

In [4]:
#Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array:
data = ([5,3,4],[4,5,6])
arr2 = np.array(data)
arr2

array([[5, 3, 4],
       [4, 5, 6]])

## There are a number of array creation functions:
- np.array()
- asarray(): convert input to ndarrray but do not copy if the input is already an ndarray.
- arange: like range: 
    - np.arange(15)
    - Out[12]: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
- Ones: 
    - np.ones(5)
    - Out[13]: array([1., 1., 1., 1., 1.])
- Zeros: 
    - np.zeros(5)
    - Out[14]: array([0., 0., 0., 0., 0.])
- empty: 
    - np.empty((1,2,2))
    - Out[19]: 
    - array([[[6. , 7.5]
  			 [8. , 1. ]]])
	Creates one array, 2 lists, 2 values
- Full: produce an array of the given shape and dtype with  all values set to the indicated “fill value”
    - np.full(3,3,dtype=np.float64)
    - Out[24]: array([3., 3., 3.])
    - full_like: takes another array and produces a filled array of the same shape and dtype
- eye, identity: create a square N x N identity match


## Data Types for ndarrays
dtype is a special object containing the information the ndarray needs to interpret a chunk of memory as a particular type of data:

In [7]:
arr3 = np.array([1,2,3,4], dtype = np.float64)

In [12]:
arr3

array([1., 2., 3., 4.])

In [13]:
arr3.dtype

dtype('float64')

In [14]:
#If we want to change the data type of our array:
arr3.astype(np.int64)
#Could assign this to a new variable and store it there

array([1, 2, 3, 4])

Note: If you're converting floating points to integers, the decimal will be lost

In [16]:
#Can also use another arrays dtype attribute
int_arr = np.arange(7)

calibers = np.array([.22,.35,.44])

int_arr.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6.])