## Transposing Arrays and Swapping Axis
Special form of reshaping that similarly returns a view on the underlying data without copying anything.

In [1]:
import numpy as np

In [3]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Now we have 3 across and 5 down, thus swapping length of each axis.

When doing matrix computations, you may use np.dot very often. For example, computing the inner matric product 

In [7]:
arr = np.random.randn(6,3)
arr

array([[ 1.46950802, -0.56874401, -0.64960228],
       [-0.25107903, -1.32129083, -0.21766954],
       [ 0.86557278,  0.07228522,  0.72183185],
       [-1.5110117 , -0.96052437, -1.18211199],
       [-1.09099763, -0.92615793, -0.96091306],
       [ 1.06979044,  0.51841337,  0.07689906]])

In [8]:
np.dot(arr, arr.T)

array([[ 2.9049067 ,  0.52391222,  0.76195075, -0.9062487 , -0.45227167,
         1.22726733],
       [ 0.52391222,  1.85623017, -0.46995778,  1.90582517,  1.70681212,
        -0.97031536],
       [ 0.76195075, -0.46995778,  1.27548262, -2.2306084 , -1.70490304,
         1.0189633 ],
       [-0.9062487 ,  1.90582517, -2.2306084 ,  4.60315218,  3.6740143 ,
        -2.20531785],
       [-0.45227167,  1.70681212, -1.70490304,  3.6740143 ,  2.97139826,
        -1.7211648 ],
       [ 1.22726733, -0.97031536,  1.0189633 , -2.20531785, -1.7211648 ,
         1.41911747]])

### Swapaxes

In [12]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [13]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])